---
title: "Chapter 4 Class"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

## 행렬식

### 정의에 의한 계산

#### 예제 4.2

```{r}
(A <- matrix(c(1, 2, -1, 2, 1, 0, 3, 4, 2), 3))
det(A)
```

### 소행렬식에 의한 계산

#### R을 이용한 소행렬식과 여인자의 계산

```{r, minor ans cofactor}
minor <- function(A, i, j){
  det(A[-i, -j, drop = FALSE])
}
cofactor <- function(A, i, j){
  (-1)^(i+j)*minor(A, i, j)
}
dump(list = c("minor", "cofactor"), file = "./cofactor.R")
```

#### 예제 4.3

```{r, example 4.3}
source("./cofactor.R")
minor(A, 1, 1)
minor(A, 2, 1)
minor(A, 3, 1)
cofactor(A, 1, 1)
cofactor(A, 2, 1)
cofactor(A, 3, 1)
cofactor.A.1 <- outer(1:3, 1, Vectorize(function(i, j) cofactor(A, i, j)))
str(A[, 1])
A[, 1] %*% cofactor.A.1
# A[, 1, drop = FALSE] %*% cofactor.A.1
A[, 1, drop = FALSE] %*% t(cofactor.A.1)
t(A[, 1, drop = FALSE]) %*% cofactor.A.1
det(A)
```

#### 예제 4.5

```{r}
(B <- matrix(c(3, 0, 3, -2, -2, -3, 2, 4, 1, 0, -1, 0, 2, 0, 0, 0), 4))
det(B)
```

### 행렬식의 기본성질

#### 예제 4.6

```{r}
t(A)
det(t(A))
det(A)
``` 

#### 예제 4.7

```{r}
(M <- matrix(c(1, 7, 7, 4, 5, 5, 3, 2, 2), 3))
det(M)
```

#### 예제 4.8

```{r}
(A2 <- matrix(c(1, 4, 7, 2, 5, 8, 3, 6, 10), 3))
det(A2)
```

#### 예제 4.9

```{r}
(A3 <- matrix(c(1, 8, 2, 3, 17, 7, 2, 21, 1), 3))
det(A3)
A4 <- A3
A3[2, ]
A3[1, ]
4*A3[1, ]
(A4[2, ] <- A3[2, ] + 4*A3[1, ])
A4
det(A4)
```

#### 예제 4.10

```{r}
(A5 <- matrix(c(1, 3, 2, 8), 2))
(B5 <- matrix(c(4, 6, 3, 6), 2))
A5 %*% B5
det(A5 %*% B5)
det(A5)
det(B5)
det(A5)*det(B5)
```

### 기본 행 연산

1. $i$번째 행과 $j$번째 행을 교환한다. $E_{ij}$
2. $i$번째 행에 $0$이 아닌 실수 $\lambda$를 곱한다.  $R_{ii}(\lambda)$
3. $j$번째 행에 $0$이 아닌 실수 $\lambda$를 곱하여 $i$번째 행에 더한다. $P_{ij}(\lambda)$.

#### 정리

$A$가 $m\times n$ 행렬이고 기본행렭 $E$가 단위행렬 $I_n$에서 이떤 한번의 기본행연산을 행하여 얻어진 것일 때,
$E\_A$는 $A$에 같은 행연산을 행하여 얻어진 것과 같다.

#### 4.4.2 (행 교환)

```{r}
(E.12 <- diag(3)[c(2, 1, 3),])
(A6 <- matrix(c(2, 4, -2, 5, 9, 6, 1, -3, 8), 3))
E.12 %*% A6
A6[c(2, 1, 3),]
A6 %*% E.12
A6[, c(2, 1, 3)]
det(E.12)
```

#### 4.4.3, 예제 4.12 (한 행에 상수 곱하기)

```{r}
(R.33.5 <- matrix(c(1, 0, 0, 0, 1, 0, 0, 0, 5), 3))
A6
R.33.5 %*% A6
A6 %*% R.33.5
det(R.33.5)
```

#### 4.4.1 (한 행을 실수배하여 다른 행에 더하기)

```{r}
A3
# (P.21.4 <- matrix(c(1, 4, 0, 0, 1, 0, 0, 0, 1), 3))
(P.21.4 <- diag(3) + 4*outer(c(0, 1, 0), c(1, 0, 0)))
P.21.4 %*% A3
A4
det(P.21.4)
```

#### 예제 4.13

```{r}
(A7 <- matrix(c(4, 1, 6, 7), 2))
(A8 <- matrix(c(2, 1, 3, 7), 2))
det(A7)
det(A8)
2*det(A8)
```

#### 예제 4.14

```{r}
(A9 <- matrix(c(1, -3, 5, 0, 1, 2, 9, 0, -1), 3))
(A10 <- 3*A9)
det(A9)
det(A10)
```

#### 예제 4.15

```{r}
(A11 <- matrix(c(-3, 2, 7, 6, -4, 5, 12, -8, 9), 3))
det(A11)
```

#### 예제 4.17

```{r}
(A12 <- matrix(c(6, -1, 2, 3, 4, 5, 0, 7, 9), 3))
det(A12)
(A13 <- A12)
A13[, 1] <- A13[, 1] + (-2)*A13[, 2]
A13
det(A13)
(A14 <- A12[c(3, 2, 1),])
det(A14)
```

#### 한 행의 배수에 다른 행을 더하기

```{r}
(A15 <- matrix(c(2, 5, 3, 9), 2))
det(A15)
(L1 <- matrix(c(1, 0, 2, 1), 2))
L1 %*% A15
A16 <- A15
(A16[1, ] <- A15[1, ] + 2*A15[2, ])
A16
det(A16)
(L2 <- matrix(c(2, 0, 1, 1), 2))
L2 %*% A15
A17 <- A15
(A17[1, ] <- 2*A15[1, ] + A15[2, ])
A17
det(A17)
```

### 자료 저장

```{r}
save.image("chapter_4_class.rda")
```