---
title: "matrix_lab 1602"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

# 제1장 연습문제

## 1.


### a.

```{r, 1.a}
M <- matrix(c(17, 19, 21, 31, 27, 23, 26, 16, 15, 11, 14, 16), ncol = 4, nrow = 3)
M
# M1 <- matrix(c(17, 31, 26, 11, 19, 27, 16, 14, 21, 23, 15, 16), ncol = 4, byrow = TRUE)
# M1
rowSums(M)
(a1. <- rowSums(M)[1])
(a2. <- rowSums(M)[2])
(a3. <- rowSums(M)[3])
c(a1., a2., a3.)
str(c(a1., a2., a3.))
c(a1. = a1., a2. = a2., a3. = a3.)
str(c(a1. = a1., a2. = a2., a3. = a3.))
c("a1." = a1., "a2." = a2., "a3." = a3.)
c("a1." = a1., "a2." = a2., "a3." = a3.)
M.row <- c(a1., a2., a3.)
M.row
names(M.row) <- c("a1.", "a2.", "a3.")
# names(M.row) <- paste("a",1:4, ".", sep = "")
M.row
str(M.row)
apply(M, 1, sum)
```

### b.

```{r, 1.b}
colSums(M)
a.1 <- colSums(M)[1]
a.2 <- colSums(M)[2]
a.3 <- colSums(M)[3]
a.4 <- colSums(M)[4]
c(a.1, a.2, a.3, a.4)
c(a.1 = a.1, a.2 = a.2, a.3 = a.3, a.4 = a.4)
M.col <- c(a.1, a.2, a.3, a.4)
M.col
names(M.col) <- paste("a.",1:4, sep = "")
M.col
str(M.col)
apply(M, 2, sum)
```

### c.

```{r, 1.c}
sum(M.row)
sum(M.col)
sum(M)
a.. <- sum(M)
a..
names(a..) <- "a.."
a..
```

### d.

```{r, 1.d}
M[1, 1]
M[2, 2]
M[3, 3]
c1 <- matrix(c(1, 2, 3, 1, 2, 3), ncol = 2)
M[c1]
(c2 <- matrix(c(1:3, 2:4), ncol = 2))
M[c2]
(c3 <- matrix(c(1, 2, 1, 3), ncol = 2))
M[c3]
(c4 <- matrix(c(1, 3, 3, 4), ncol = 2))
M[c4]
sum(M[c1])
rep(1:3, times = 2)
c5 <- matrix(rep(1:3, 2), ncol = 2)
M[c5]
rep(1:3, each = 2)
c6 <- matrix(rep(1:3, each = 2), ncol = 2, byrow = TRUE)
M[c6]
```

### e.

```{r, 1.e}
M[, -2]
# M[, c(1, 3, 4)]
rowSums(M[, -2])
```

### f.

```{r, 1.f}
M[-2, -3]
sum(M[-2, -3])
```

## 2.

```{r, 2}
A <- matrix(c(-1, 3, 11, -6, 17, 13, -9, -8, 9, 10, 0, 1, -2, 2, -3, 4, 3, 6, 2, 5), ncol = 5)
A
```

### a.

```{r, 2.a}
a1. <- rowSums(A)[1]
a.3 <- colSums(A)[3]
c(a1. = a1., a.3 = a.3)
```

### b.

```{r, 2.b}
A[1:3, 2, drop = FALSE]
A[-4, 2, drop = FALSE]
sum(A[-4, 2])
A[c(1, 3, 4), 5]
A[-2, 5]
sum(A[-2, 5])
```

### c.

```{r, 2.c}
rowSums(A)
rowSums(A)[3:4]
rowSums(A)[3:4]^2
sum((rowSums(A)[3:4])^2)
a.. <- sum(A)
names(a..) <- "a.."
a..
```

### d.

```{r, 2.d}
A[c(1, 3, 4), c(2, 3, 5)]
A[-2, -c(1, 4)]
sum(A[-2, -c(1, 4)])
A[4, 1:3, drop = FALSE]
prod(A[4, 1:3])
A[1:4, 4, drop = FALSE]
A[, 4, drop = FALSE]
prod(A[1:4, 4])
```

### e.

```{r, 2.e}
A[, 1, drop = FALSE]
A[, 4, drop = FALSE]
A[, 1] %*% A[, 4]
20 * a..
```

### f.

```{r, 2.f}
A2 <- A
A2[, c(1, 3, 5)] <- -A2[, c(1, 3, 5)]
A2
sum
A[2, -3]
A[4, -3]
(A[2, -3] - A[4, -3]) 
(A[2, -3] - A[4, -3]) %*% (A[2, -3] - A[4, -3])
```

## 3.

### a.

```{r. 3.a}
B <- A[2:4, 3:5]
B
```

### b.

```{r, 3.b}
C <- A[c(2, 4), c(1, 3, 5)]
C
```

### c.

```{r, 3.c}
i.minus.j <- rbind(1:(-2), 2:(-1)) 
i.minus.j
A[2:3, 1:4]
D <- A[2:3, 1:4] + i.minus.j
D
```

## 5.

### a.

```{r, 5.a}
i <- 3:5
3^i
sum(3^i)
k <- 2:7
2^k
sum(2^k)
```

### b.

```{r, 5.b}
r <- 1:5
sum(r)
s <- c(1, 3:5)
s*(s + 1)
sum(s*(s + 1))
s2 <- c(s, 6)
sum(s2*(s2 + 1))
```

### c.

```{r, 5.c}
i <- 1:4
prod(2^i)
j <- 1:2
k <- 2*j - 1
sapply(1:3, "^", k)
apply(sapply(1:3, "^", k), 2, prod)
sum(apply(sapply(1:3, "^", k), 2, prod))
```

## 6.

```{r, 6}
D1 <- diag(1:4)
D1
D2 <- diag(3^(1:4-2))
D2
D3 <- D1 + D2
D3
D4 <- diag(1:4 + 3^(1:4-2))
D4
```

```{r, save}
save.image(file="chap_01_lab1602.rda")
#savehistory(file="chap_01.Rhistory")
```