---
title: "Chapter_2_lab"
author: "coop711"
date: "2015년 9월 14일"
output: html_document
---

## 1.

```{r}
(A1 <- matrix(c(3, 2, 6, 1), 2))
(B1 <- matrix(c(1, 0, 0, -1, 3, -1, 2, 1), 2))
(X1 <- matrix(c(1, 1, 0, -1), 4))
(Y1 <- matrix(c(1, -1), 2))
```

(a)

```{r}
A1 %*% B1
t(A1) %*% B1
```

(b)

```{r}
(A1 + t(A1)) 
(A1 + t(A1)) %*% B1
A1 %*% B1
t(A1) %*% B1
A1 %*% B1 + t(A1) %*% B1
```

(c)

```{r}
t(B1)
B1 %*% t(B1)
t(B1) %*% B1
```

(d)

```{r}
tr.f <- function(x) {sum(diag(x))}
B1 %*% t(B1)
tr.f(B1 %*% t(B1))
t(B1) %*% B1
tr.f(t(B1) %*% B1)
```

(e)

```{r}
A1 %*% A1 - 4*A1 - 9*diag(2)
```

## 2.

(a)

```{r}
matrix(c(rep(1, 4)), 2) 
matrix(c(2, 3, 3, 2), 2)
matrix(c(rep(1, 4)), 2) %*% matrix(c(2, 3, 3, 2), 2)
matrix(c(2, 3, 3, 2), 2) %*% matrix(c(rep(1, 4)), 2)
```

(b)

```{r}
(A2 <- (1/3)*matrix(rep(1, 9), 3))
A2 %*% A2
```

(c)

```{r}
(B2 <- 1/sqrt(6)*matrix(c(1, -2, 1, sqrt(2), sqrt(2), sqrt(2), sqrt(3), 0, -sqrt(3)), 3))
t(B2)
B2 %*% t(B2)
t(B2) %*% B2
```

(d)

```{r}
(C2 <- matrix(c(6, 9, -4, -6), 2))
C2 %*% C2
```

(e)

```{r}
matrix(c(4, 1, 4, -5, 1, 4, -1, 2, -1), 3)
matrix(c(1, -1, 0, 1, 0, 4, 1, 1, -1), 3)
(1/9)*matrix(c(4, 1, 4, -5, 1, 4, -1, 2, -1), 3) %*% matrix(c(1, -1, 0, 1, 0, 4, 1, 1, -1), 3)
```

## 3.

```{r}
(X3 <- matrix(c(1, 0, -1, 2, -1, 0, 3, -2, 7), 3))
(Y3 <- matrix(c(6, -3, 0, 0, 4, -5, 0, 0, 2), 3))
X3 %*% X3
Y3 %*% Y3
X3 %*% Y3
Y3 %*% X3
X3 + Y3
(X3 + Y3) %*% (X3 + Y3)
X3 %*% X3 + X3 %*% Y3 + Y3 %*% X3 + Y3 %*% Y3
```

## 4.

```{r}
(A4 <- matrix(c(1, 0, 2, 0, 1, 0, 2, 1, 2), 3))
(B4 <- matrix(c(1, 0, 2, 3, 4, 3, 0, -1, 0), 3))
(X4 <- matrix(c(6, 2, 3, 5, 2, 3, 7, 4, 6), 3))
A4 %*% X4
B4 %*% X4
```

## 7.

```{r}
(A7 <- matrix(c(1, 2, 2, 3), 2))
(B7 <- matrix(c(1, 2, 0, -1), 2))
(C7 <- matrix(c(1, 4, 3, 5), 2))
A7 %*% B7 %*% C7
tr.f(A7 %*% B7 %*% C7)
B7 %*% A7 %*% C7
tr.f(B7 %*% A7 %*% C7)
```

## 8.

```{r}
(A8 <- matrix(c(-1, 7, 2, 3), 2))
(B8 <- matrix(c(6, 2, 8, 3, -1, 1, 0, 4), 2))
(x8 <- matrix(c(1, 1, 2, 3), 4))
```

(a)

```{r}
A8 + t(A8) 
(A8 + t(A8)) %*% B8
A8 %*% B8
t(A8) %*% B8
A8 %*% B8 + t(A8) %*% B8
```

(b)

```{r}
t(B8) %*% B8
tr.f(t(B8) %*% B8)
B8 %*% t(B8)
tr.f(B8 %*% t(B8))
```

(c)

```{r}
t(x8) %*% t(B8) %*% B8 %*% x8
B8 %*% x8
t(B8 %*% x8) %*% (B8 %*% x8)
t(B8) %*% B8
x8 %*% t(x8)
t(B8) %*% B8 %*% x8 %*% t(x8)
tr.f(t(B8) %*% B8 %*% x8 %*% t(x8))
```

## 9.

```{r}
(A9 <- matrix(c(2, 6, 3, 1, 7, -2), 2))
(B9 <- matrix(c(-1, 0, 0, 1, 1, 7), 2))
A9 + B9
t(A9 + B9)
(A9 + B9) %*% t(A9 + B9)
(A9 + B9) %*% (t(A9) + t(B9))
A9 %*% t(A9) 
A9 %*% t(B9)
B9 %*% t(A9)
B9 %*% t(B9)
A9 %*% t(A9) + A9 %*% t(B9) + B9 %*% t(A9) + B9 %*% t(B9)
t(A9 + B9) %*% (A9 + B9) 
```

## 10.

```{r}
(P.cost <- matrix(c(40, 38, 41), 3))
(T.cost <- matrix(c(10, 14, 6, 15, 8, 14, 9, 12, 22, 7, 8, 17), 3))
(sum.vector <- matrix(rep(1, 4), 4))
(Total.cost <- P.cost + T.cost %*% sum.vector)
```

## 자료 갈무리

```{r}
save.image("chapter_2_lab.rda")
```
