---
title: "Chapter_2_class"
author: "coop711"
date: "2015년 9월 14일"
output: html_document
---

# 행렬의 기본연산과 성질

## 행렬의 전치

```{r}
matrix(c(8, 9, 6, 9, 7, 13, -3, 11, 11, 6, 4, 8), nrow=4)
(A1 <- matrix(c(8, 9, 6, 9, 7, 13, -3, 11, 11, 6, 4, 8), 4))
```

* 전치행렬 $A1^t$은 다음과 같이 주어짐.

```{r}
t(A1)
```

* 몇 가지 성질을 살펴보면,

```{r}
A1[1, 2]
A1[1, 2, drop = FALSE]
(t(A1))[2, 1]
t(t(A1))
```

* 벡터의 경우,

```{r}
(x1 <- matrix(c(1, 6, 4), 3))
str(x1)
t(x1)
x2 <- c(1, 6, 4)
str(x2)
t(x2)
```

## 행렬의 분할

* 분할 행렬

```{r, example 2.2}
(A2 <- matrix(c(1, 2, 4, 9, 6, 6, 4, 3, 1, 8, 8, 1, 6, 4, 1, 9, 6, 1, 6, 4, 3, 1, 2, 8, 3, 8, 1, 5, 7, 2), nrow = 5))
c1 <- c(1, 2, 4, 9, 6)
c2 <- c(6, 4, 3, 1, 8)
c3 <- c(8, 1, 6, 4, 1)
c4 <- c(9, 6, 1, 6, 4)
c5 <- c(3, 1, 2, 8, 3)
c6 <- c(8, 1, 5, 7, 2)
A2.2 <- cbind(c1, c2, c3, c4, c5, c6)
A2.2
# (A2.11 <- A2.2[1:3, 1:4])
# (A2.12 <- A2.2[1:3, 5:6])
# (A2.21 <- A2.2[4:5, 1:4])
# (A2.22 <- A2.2[4:5, 5:6])
(A2.11 <- A2[1:3, 1:4])
(A2.12 <- A2[1:3, 5:6])
(A2.21 <- A2[4:5, 1:4])
(A2.22 <- A2[4:5, 5:6])
```

* 분할행렬의 전치

```{r}
cbind(A2.11, A2.12)
t(cbind(A2.11, A2.12))
rbind(t(A2.11), t(A2.12))
t(A2)
rbind(cbind(t(A2.11), t(A2.21)), cbind(t(A2.12), t(A2.22)))
```

## 행렬의 궤적

* 정방행렬에 대하여 정의

```{r}
(A3 <- matrix(c(-2, 3, 7, 4, 8, -2, 5, 1, 6), 3))
diag(A3)
sum(diag(A3))
psych::tr(A3)
```

* 전치행렬의 궤적(trace)

```{r}
(B3 <- matrix(c(1, 7, 6, 8, 3, 9, 4, -2, -8), 3))
diag(B3)
sum(diag(B3))
t(B3)
diag(t(B3))
sum(diag(t(B3)))
```

* `trace` 계산하는 함수를 정의하여 사용한다면,

```{r}
tr.f <- function(x) {sum(diag(x))}
tr.f(B3)
tr.f(t(B3))
dump("tr.f", file = "./tr_f.R")
```

## 행렬의 연산

### 행렬의 덧셈

```{r}
source("./tr_f.R")
ls()
(A4 <- matrix(c(1, 5, 2, 1, 4, 2), 2))
(B4 <- matrix(c(2, -1, 5, 0, 1, 3), 2))
(C4 <- A4 + B4)
A4 - B4
t(C4)
t(A4) + t(B4)
(D4 <- rbind(A4, c(0, 0, 1)))
(E4 <- rbind(B4, c(0, 0, 1)))
D4 + E4
tr.f(D4 + E4)
tr.f(D4)
tr.f(E4)
tr.f(D4) + tr.f(E4)
```

### 행렬의 곱셈 

* 벡터의 내적

```{r}
x4 <- c(2, -3, 4, 1)
y4 <- c(4, 2, 6, -1)
x4 * y4
x4 %*% y4
```

### 행렬의 곱셈 

* 예제 2.4

```{r}
(A5 <- matrix(c(1, -1, 0, 4, 2, 3), 2))
(B5 <- matrix(c(0, 1, 3, 6, 1, 4, 1, 0, 4, 5, 7, 3), 3))
A5 %*% B5
```

### 행렬 곱셈의 교환성 

* 예제 2.5

```{r}
(A6 <- matrix(c(1, 3, 2, 4), 2))
(B6 <- matrix(c(0, 1, -1, -1), 2))
A6 %*% B6
B6 %*% A6
```

* $(AB)^\prime = B^\prime A^\prime$

```{r}
t(A6 %*% B6)
t(B6) %*% t(A6)
```

## 행렬의 대수법칙

* 결합법칙, 분배법칙, 교환법칙 되는 경우와 안 되는 경우

* 특이한 경우

```{r}
(A7 <- matrix(c(1, 3, 2, 4), 2))
(B7 <- matrix(c(0, 3, 2, 3), 2))
A7 %*% B7
B7 %*% A7
```

## 스칼라 대수와의 비교

* $AB = 0$ 이면 $A$ 또는 $B$가 $0$?

```{r}
(A8 <- matrix(rep(1, 4), 2))
(B8 <- matrix(rep(c(1, -1), 2), 2))
A8 %*% B8
```

* $X^2 = 0$ 이면 $X = 0$?

```{r}
(X8 <- matrix(c(1, 2, -1, 2, 4, -2, 5, 10, -5), 3))
X8 %*% X8
```

* 주의 : R 기호에서, `X^2`과 `X %*% X`는 서로 다른 것임.

```{r}
X8^2
X8 %*% X8
```

* $X^2 = I$ 라고 해서 $X = I$ 혹은 $X = -I$인 것은 아니임.

```{r}
(X9 <- matrix(c(1, 4, 0, -1), 2))
X9 %*% X9
```

* $X^2 = X$ 이더라도 $X \ne 0$ 이고  $X \ne I$일 수 있음.

```{r}
(X10 <- matrix(c(3, 3, -2, -2), 2))
X10 %*% X10
```

### 자료 갈무리

```
save.image(file="chapter_2_class.rda")
```
