---
title: "중간고사"
author: "학번__________, 이름__________"
date: "2015년 10월 20일"
output: html_document
---

#### 1. 행렬 $A = \{a_{ij}\}$에 대하여 다음 계산을 확인하고, R로 옳게 표현한 것을 고르시오. (36점)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; $A=\begin{bmatrix} -1&17&9&-2&3\\3&13&10&2&6\\11&-9&0&-3&2\\-6&-8&1&4&5\end{bmatrix} = \{a_{ij}\}$

```{r, echo = FALSE, results='hide'}
A <- matrix(c(-1, 3, 11, -6, 17, 13, -9, -8, 9, 10, 0, 1, -2, 2, -3, 4, 3, 6, 2, 5), 4)
```

##### (a)(6점)  $a_{1.} = 26$, $a_{.3} = 20$ 

(풀이)

----

----

----

----

----

(R 표현)

가. `rowSums(A)[, 1]`, `colSums(A)[3, ]`

나. `rowSums(A)[, 1]`, `colSums(A)[, 3]`

다. `rowSums(A)[1]`, `colSums(A)[3]`

라. `rowSums(A)[1, ]`, `colSums(A)[, 3]`

----

##### (b)(6점)  $\sum_{i=1}^{3}a_{i2} = 21$, $\sum_{i=1,i\ne2}^4a_{i5} = 10$

(풀이)

-----

-----

-----

-----

----

(R 표현)

가. `sum(A[1:3, 2])`, `sum(A[-2, 5])`

나. `sum(A[-4, 2])`, `sum(A[2, 5])`

다. `sum(A[1:3, 2])`, `sum(A[2, -5])`

라. `sum(A[4, 2])`, `sum(A[c(1, 3, 4), 5])`

----

##### (c)(6점) $\sum_3^4a_{i.}^2 = 17$, $a_{..} = 57$

(풀이)

-----

-----

-----

-----

(R 표현)

가. `sum((rowSums(A)[3:4, ])^2)`, `(a.. <- sum(A))`

나. `sum((rowSums(A)[3:4])^2)`, `(a.. <- sum(A))`

다. `sum((rowSums(A)[, 3:4])^2)`, `(a.. <- sum(A))`

라. `(sum(rowSums(A)[3:4]))^2`, `(a.. <- sum(A))`

----

##### (d)(8점) $\sum_{i=1, i\ne2}^4\sum_{j=2,j\ne4}^5a_{ij}=20$, $\prod_{j=1}^3a_{4j}=\prod_{i=1}^4a_{i4}=48$.

(풀이)

-----

-----

-----

-----


(R 표현)

가. `sum(A[-2, c(2, 3, 5)])`, `prod(A[1:3, 4])`, `prod(A[1:4, 4])`

나. `sum(A[-2, -c(1, 4)])`, `prod(A[4, 1:3])`, `prod(A[4, 1:4])`

다. `sum(A[-2, -c(1, 4)])`, `prod(A[1:3, 4])`, `prod(A[1:4, 4])`

라. `sum(A[-2, c(2, 3, 5)])`, `prod(A[4, 1:3])`, `prod(A[1:4, 4])`

----

##### (e)(6점) $\sum_{i=1}^4a_{i1}a_{i4} = -49$, $\sum_{i=1}^4\sum_{j=1}^5a_{..}=1140$.

(풀이)

-----

-----

-----

-----


(R 표현)

가. `A[, 1] %*% A[, 4]`, `20 * sum(A)`

나. `A[1, ] %*% A[, 4]`, `20 * sum(A)`

다. `A[, 1] %*% A[4, ]`, `20 * sum(A)`

라. `A[1, ] %*% A[4, ]`, `20 * sum(A)`

----

##### (f)(4점) $i=2$ 일 때, $\sum_{j=1, j\ne3}^5(a_{ij}-a_{i+2,j})^2=527$

(풀이)

-----

-----

-----

-----

-----

(R 표현)

가. `(A[2, -3]-A[4, -3]) %*% (A[2, -3]-A[4, -3])`

나. `(A[-2, 3]-A[4, -3]) %*% (A[-2, 3]-A[4, -3])`

다. `(A[2, -3]-A[-4, 3]) %*% (A[2, -3]-A[-4, 3])`

라. `(A[-2, 3]-A[-4, 3]) %*% (A[-2, 3]-A[-4, 3])`

----

#### 2. (6점)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 모든 $i=1,\ 2,\ \ldots,\ m$ 에 대하여 $x_i=\sum_{j=1}^n\lambda_{ij}v_j$, $\sum_{j=1}^n\lambda_{ij}=1$, 그리고 $\sum_{i=1}^m\mu_i=1$일 때, $\sum_{i=1}^m \mu_i x_i$에서 $v_j$의 계수들의 합이 1이 됨을 보이시오.

##### (a)(3점) $\sum$ 기호를 이용하시오.

-----

-----

-----

-----

-----

----

----

----

----

----

----

##### (b)(3점) summing vector $1^t=(1, 1, \ldots, 1)$ 를 이용하시오.

-----

-----

-----

----

----

----

----

----

----

----

#### 3. (18점)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; $A=\begin{bmatrix}3&6\\2&1\end{bmatrix}$, 
$B=\begin{bmatrix}1&0&3&2\\0&-1&-1&1\end{bmatrix}$ 에 대하여 다음을 계산하시오.

##### (a)(4점) 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; $A\ B, 그리고 $A^tB$

----

----

----

----

##### (b)(4점)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; $(A+A^t)B$, $A\ B+A^tB$

----

----

----

----

##### (c)(4점)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; $B\ B^t$, 그리고 $B^tB$

----

----

----

----

----

----

##### (d)(4점)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ${\rm tr}(B\ B^t) = {\rm tr}(B^tB)$

----

----

----

----

----

----

##### (e)(2점)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; $A^2-4A-9I=0$.

----

----

----

----

----

----

----

#### 4. (5점)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; $A=\begin{bmatrix}1&1\\2&1\end{bmatrix}$, $B=\begin{bmatrix}3&6\\4&8\end{bmatrix}$, $x=\begin{bmatrix}1\\2\end{bmatrix}$, $y=\begin{bmatrix}3\\4\end{bmatrix}$일 때, 다음 표현 중에서 어떤 것이 정의될 수 없는가? 

##### (a) $y=A\ x$
##### (b) $x\ y=A^tB$
##### (c) $x^tB\ x$
##### (d) $y\ B\ x$
##### (e) $y^tB^tA\ x$
##### (f) $x^t=y^tB^t$
##### (g) $x^tA\ y$
##### (h) $y^tA^tB\ y$
##### (i) $x\ y^t=B^t$
##### (j) $y+\begin{bmatrix}30\\40\end{bmatrix}=A\ B^tx$

#### 5. (5점)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; $X^tX=X$ 이면 $X=X^t=X^2$임을 보여라.

----

----

----

----

----

----

----

----

----

----

----

----

----

----

----

----

----

----

----

----

----

----

----

----

----


#### 6. 다음 행렬식들의 값을 확인하여라. (10점)

##### (a)(4점)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; $\begin{vmatrix}1&5&-5\\3&2&-5\\6&-2&-5\end{vmatrix}=-5$

----

----

----

----

##### (b)(2점)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; $\begin{vmatrix}1&-1&-1&-1\\-1&1&-1&-1\\-1&-1&1&-1\\-1&-1&1&-1\end{vmatrix}=0$

----

----

----

----

----

##### (c)(4점)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; $\begin{vmatrix}21&6&3&9\\12&16&36&4\\13&10&19&5\\1&93&81&6\end{vmatrix}=0$

----

----

----

----

----

----

----

----

----

----

----

----

----

----

----

----

----

----


#### 7. 다음을 보여라. (10점)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; $\begin{vmatrix}a+b+c&a+b&a&a\\a+b&a+b+c&a&a\\a&a&a+b+c&a+b\\a&a&a+b&a+b+c\end{vmatrix}=c^2(4a+2b+c)(2b+c)$

----

----

----

----

----

----

----

----

----

----


#### 8. R에서 다음 계산 결과는 어떻게 나오는가? (4점)

##### (a)(2점) `diag(1:3)`

----

----

----

##### (b)(2점) `diag(3)`

----

----

----

#### 9. R에서 다음의 계산 결과는 어떻게 나타나는가? (6점)


##### (a)(2점) `(M <- matrix(1:4, 2))`

----

----

----

##### (b)(2점) `M[, 2]`

----

----

----


##### (c)(2점) `M[, 2, drop = FALSE]`

----

----

----

----

----

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*"There's a difference between knowing the path and walking the path." (Morpheus, The Matrix)*