---
title: "Part I Chapter 2"
output: html_document
---


```{r, options}
options(scipen = 7)
```

#### 13쪽 설명

```{r, pp13, fig.width = 4, fig.height = 4}
x <- c(1.0, 1.5, 1.8, 1.9, 1.95, 1.99, 1.995, 1.999, 3.0, 2.5, 2.2, 2.1, 2.05, 2.01, 2.005, 2.001)
y <- x^2 - x + 2
curve(x^2 - x + 2, -4, 4)
plot(x, y, pch = 20)
plot(x, y, xlim = c(1.5, 2.5), ylim = c(2, 6), pch = 20)
plot(x, y, xlim = c(1.8, 2.2), ylim = c(3, 5), pch = 20)
plot(x, y, xlim = c(1.9, 2.1), ylim = c(3.5, 4.5), pch = 20)
```


#### 예제 1 

```{r, example 1, fig.width = 4, fig.height = 4}
x <- c(0.5, 0.9, 0.99, 0.999, 0.9999)
y <- (x - 1)/(x^2 - 1)
curve((x - 1)/(x^2 - 1), -2, 2, ylim = c(-10, 10))
points(1, 0.5)
abline(v = -1, h = 0, lty =2)
curve((x - 1)/(x^2 - 1), -2, 2, ylim = c(-10, 10))
points(1, 0.5)
abline(v = -1, h = 0, lty =2)
points(1, 2, pch = 20)
```

#### 예제 2

```{r, example 2, fig.width = 4, fig.height = 4}
x <- c(-1., -0.5, -0.1, -0.05, -0.01, -0.0005, -0.0001, -0.00005, -0.00001, 0.00001, 0.00005, 0.0001, 0.0005, 0.01, 0.05, 0.1, 0.5, 1.)
y <- (sqrt(x^2 + 9) - 3)/x^2
cbind(x, y)
plot(x, y, pch = 20)
curve((sqrt(x^2 + 9) - 3)/x^2, -2, 2)
points(0, 1/6)
```

#### 2.1-15

```{r, 2.1-15, fig.width = 4, fig.height = 4}
x <- seq(0.01, 10, length = 100)
y <- (1 + x)^(1/x)
curve((1 + x)^(1/x), 0.00001, 5)
plot(x, y, pch = 20)
```

#### 2.2-11

```{r, 2.2-11, fig.width = 4, fig.height = 4}
curve(x/(x^2 + 5*x + 6), -5, 0)
abline(v = c(-3, -2), h = 0, lty = 2)
```

#### 2.3-16

```{r, 2.3-16, fig.width = 4, fig.height = 4}
curve(x/(sqrt(1 + 3*x) - 1), -1/3, 2)
x <- c(-0.3, -0.1, -0.05, -0.01, -0.005, -0.001, -0.0005, -0.0001, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.3)
y <- x/(sqrt(1 + 3*x) - 1)
cbind(x, y)
curve((sqrt(1 + 3*x) + 1)/3, -1/3, 2)
```

#### 2.4-12

```{r, 2.4-16}
(x <- seq(-3.2, -2.8, by = 0.01))
1/(x + 3)^4 > 10000
which(1/(x + 3)^4 > 10000)
x[1/(x + 3)^4 > 10000]
```