---
title: "Part I Chapter 1 Lab"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r, echo=FALSE}
library(pander)
library(knitr)
```

#### 1.1

##### 1.1.1 $f(x)=1+x^2$

```{r, 1.1.1, fig.width=4, fig.height=4}
curve(1 + x^2, -5, 5)
```

##### 1.1.2 $f(x)=1-\sqrt{x}$

```{r, 1.1.2, fig.width=4, fig.height=4}
curve(1 - sqrt(x), 0, 25)
```

##### 1.1.3 $f(x)=\frac{1}{\sqrt{x}}$

```{r, 1.1.3, fig.width=4, fig.height=4}
curve(1 / sqrt(x), 0, 100)
```

##### 1.1.4 $f(x)=\frac{1}{1+\sqrt{\,x}}$

```{r, 1.1.4, fig.width=4, fig.height=4}
curve(1 / (1 + sqrt(x)), 0, 25)
```

##### 1.1.5 $f(x)=\sqrt{4-x^2}$

```{r, 1.1.5, fig.width=4, fig.height=4}
curve(sqrt(4 - x^2), -2, 2)
```

##### 1.1.6 $f(x)=\frac{1}{\sqrt{9-x^2}}$

```{r, 1.1.6, fig.width=4, fig.height=4}
curve(1/sqrt(9 - x^2), -3, 3)
```

##### 1.1.7 $f(x)=\sqrt{\frac{1}{x}-1}$

```{r, 1.1.7, fig.width=4, fig.height=4}
curve(sqrt(1/x - 1), 0, 1)
```

##### 1.1.8 $f(x)=\sqrt{2-\sqrt{x}}$

```{r, 1.1.8, fig.width=4, fig.height=4}
curve(sqrt(2 - sqrt(x)), 0, 4)
```

#### 1.2

##### 1.2.1 $f(x)=5-2x$

```{r, 1.2.1, fig.width=4, fig.height=4}
x <- seq(-5, 5, length=100)
y <- 5 - 2 * x
plot(x, y, ylab=expression(y == 5 - 2*x), type="l")
```

##### 1.2.2 $f(x)=1-2x-x^2$

```{r, 1.2.2, fig.width=4, fig.height=4}
x <- seq(-5, 3, length=100)
y <- 1 - 2*x - x^2
plot(x, y, ylab=expression(y == 1 - 2*x - x^2), type="l")
```

##### 1.2.3 $f(x)=\sqrt{|\,x\,|}$

```{r, 1.2.3, fig.width=4, fig.height=4}
x <- seq(-25, 25, length=100)
y <- sqrt(abs(x))
plot(x, y, ylab=expression(y == sqrt(abs(x))), type="l")
```

##### 1.2.4 $f(x)=\sqrt{-x}$

```{r, 1.2.4, fig.width=4, fig.height=4}
x <- seq(-25, 0, length=100)
y <- sqrt(-x)
plot(x, y, ylab=expression(y == sqrt(-x)), type="l")
```

##### 1.2.5 $f(x)=\frac{x}{|\,x\,|}$

```{r, 1.2.5, fig.width=4, fig.height=4}
x <- seq(-5, 5, length=99)
y <- x/abs(x)
plot(x, y, ylab=expression(y == x/abs(x)), type="l")
```

##### 1.2.6 $f(x)=\frac{1}{|\,x\,|}$

```{r, 1.2.6, fig.width=4, fig.height=4}
x <- seq(-5, 5, length=99)
y <- 1/abs(x)
plot(x, y, ylab=expression(y == 1/abs(x)), type="l")
```

##### 1.2.7 $|\,y\,|=x$

```{r, 1.2.7, fig.width=4, fig.height=4}
y <- seq(-5, 5, length=99)
x <- ifelse(y >= 0, y, -y)
plot(x, y, ylab=expression(abs(y) == x), type="l")
abline(h=0, v=0, lty=2)
```

##### 1.2.8 $y^2=x^2$

```{r, 1.2.8, fig.width=4, fig.height=4}
opar <- par(no.readonly=TRUE)
par(mai = c(1.02, 1.02, 0.82, 0.42))
x <- seq(-5, 5, length=99)
y1 <- ifelse(x >= 0, x, -x)
y2 <- -y1
plot(x, y1, ylab=expression(y^2==x^2), type="l", ylim=c(-5, 5))
lines(x, y2)
abline(h=0, v=0, lty=2)
par(opar)
```

##### 1.2.9 $|\,x\,|+|\,y\,|=1$

```{r, 1.2.9, fig.width=4, fig.height=4}
x <- seq(-1, 1, length=99)
y1 <- ifelse(x >= 0, 1-x,  1+x)
y2 <- -y1
plot(x, y1, ylab=expression(abs(x)+abs(y)==1), type="l", ylim=c(-1, 1))
lines(x, y2)
abline(h=0, v=0, lty=2)
```

##### 1.2.11 $f(x)=1+(4/x), g(x)=x/2$

```{r, 1.2.11, fig.width=4, fig.height=4}
x <- seq(-10, 10, length=99)
y1 <- 1 + 4/x
y2 <- x/2
plot(x, y1, ylab="y", type="l", ylim=c(-10, 10))
lines(x, y2, col="red")
abline(h=0, v=0, lty=2)
```

##### 1.2.12 $f(x)=3/(x-1), g(x)=2/(x+1)$

```{r, 1.2.12, fig.width=4, fig.height=4}
x <- seq(-9, 9, length=199)
y1 <- 3/(x - 1)
y2 <- 2/(x + 1)
plot(x, y1, ylab="y", type="l", ylim=c(-2, 2))
lines(x, y2, col="red")
abline(h=0, v=0, lty=2)
```

##### 1.3.5 $y=\frac{1}{|\,x\,|}$

```{r, 1.3.5, fig.width=4, fig.height=4}
x <- seq(-5, 5, length=99)
y <- ifelse(x >= 0, 1/x, -1/x)
plot(x, y, ylab="y", type="l", ylim=c(-6, 6))
abline(h=0, v=0, lty=2)
```

##### 1.3.6 $y=\sqrt{|\,x\,|}$

```{r, 1.3.6, fig.width=4, fig.height=4}
x <- seq(-25, 25, length=99)
y <- sqrt(abs(x))
plot(x, y, ylab="y", type="l", ylim=c(-6, 6))
abline(h=0, v=0, lty=2)
```

##### 1.3.10 $y=-x^{3/2}$

```{r, 1.3.10, fig.width=4, fig.height=4}
x <- seq(-4, 4, length=99)
y <- -x^(3/2)
plot(x, y, ylab="y", type="l", ylim=c(-8, 8))
abline(h=0, v=0, lty=2)
```

##### 1.3.11 $y=(-x)^{3/2}$

```{r, 1.3.11, fig.width=4, fig.height=4}
x <- seq(-4, 4, length=99)
y <- (-x)^(3/2)
plot(x, y, ylab="y", type="l", ylim=c(-8, 8))
abline(h=0, v=0, lty=2)
```

##### 1.3.12 $y=(-x)^{2/3}$

```{r, 1.3.12, fig.width=4, fig.height=4}
x <- seq(-8, 8, length=199)
y <- (-x)^(2/3)
plot(x, y, ylab="y", type="l", ylim=c(-4, 4))
abline(h=0, v=0, lty=2)
```

##### 1.3.13 $y=-x^{2/3}$

```{r, 1.3.13, fig.width=4, fig.height=4}
x <- seq(-8, 8, length=199)
y <- -x^(2/3)
plot(x, y, ylab="y", type="l", ylim=c(-4, 4))
abline(h=0, v=0, lty=2)
```

### 자료 저장

```{r}
save.image("Part_I_Chap_1_lab.rda")
```